### ISSUE TITLE
running code with matlab r2016b and ubuntu 16.04

### ISSUE THREAD

**Issue by juanbraga** [dpwe/alignmidi#1]
Hi,

I am having trouble to run it with r2016b. The main problem, as you may know, is that now wavread function does not exists any more, instead we have audioread.

Has somebody ever tried to run it on newer matlab versions?

I would appreciate some advice.

Thanks in advance

**Comment by dpwe** [comment]
Yes.  Unfortunately I don't use Matlab any more, so I can't fix it. It
should be straightforward to find equivalent invocations of Matlab's
audioread.

  DAn.

**Comment by juanbraga** [comment]
Thanks DAn.

Regards.
